### ISSUE TITLE
Not works run tests

### ISSUE THREAD

**Issue by IvanProg00** [rouge8/neotest-rust#25] opened 2023-03-05 15:47 UTC
When I try to run the test, I get an error message:

```plain
Error executing vim.schedule lua callback: ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: The coroutine failed with this message: ...e/nvim/lazy/plenary.nvim/lua/plenary/context_manager.lua:47: /var/folders/z5/sp9btnks26sbh__fhy
tbhshc0000gn/T/nvim.ivan/B62x0s/19.junit.xml: No such file or directory
stack traceback:
        [C]: in function 'error'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:18: in function 'callback_or_next'
        ...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:45: in function <...share/nvim/lazy/plenary.nvim/lua/plenary/async/async.lua:44>
```

My test code:

```rs
#[cfg(test)]
mod tests {
    #[test]
    fn it_works() {
        assert_eq!(2 + 2, 4);
    }
}
```

But this error I have only in `Rust`, in `Go` works good.

[Here is my Neovim config.](https://github.com/IvanProg00/AstroNvim/blob/154d65148134e072610e1e3ac0c70a746d4a48bd/plugins/init.lua#L172-L203)

**Comment by rouge8** [comment] 2023-03-05 17:40
I think this is a duplicate of https://github.com/rouge8/neotest-rust/issues/20

**Closed by rouge8** 2023-03-05 17:40 UTC
